INSERT INTO tableName (book_name) VALUES ('trading_book_1');
INSERT INTO tableName (book_name) VALUES ('trading_book_2');
INSERT INTO tableName (book_name) VALUES ('Trading_book_3');
INSERT INTO tableName (book_name) VALUES ('Trading_book_2');
INSERT INTO tableName (book_name) VALUES ('Trading_book_4');
INSERT INTO tableName (book_name) VALUES ('Trading_book_6');

INSERT INTO counter_party (bond_holder) VALUES ('AZ Holdings Inc');
INSERT INTO counter_party (bond_holder) VALUES ('Acme co');
INSERT INTO counter_party (bond_holder) VALUES ('Acme Co');
INSERT INTO counter_party (bond_holder) VALUES ('Sovereign Investments');
INSERT INTO counter_party (bond_holder) VALUES ('Astra Trading Ltd');
INSERT INTO counter_party (bond_holder) VALUES ('Muncipal Gov Of Orange County');
INSERT INTO counter_party (bond_holder) VALUES ('Goldman Sachs');
INSERT INTO counter_party (bond_holder) VALUES ('UBS');
INSERT INTO counter_party (bond_holder) VALUES ('Barclays');
INSERT INTO counter_party (bond_holder) VALUES ('British Telecom');
INSERT INTO counter_party (bond_holder) VALUES ('Pension Holdings');
INSERT INTO counter_party (bond_holder) VALUES ('Zurich Pension fund 4');

INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('4.37', 'USD', '', '1000', 'XS1988387210', 'BNPParibasIssu 4,37% Microsoft Corp (USD)', '5/8/21', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('4.37', 'USD', '', '1000', 'XS1988387210', 'BNPParibasIssu 4,37% Microsoft Corp (USD)', '5/8/21', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('3.15', 'USD', '123456780', '900', 'USN0280EAR64', 'Airbus 3.15%  USD', '30/07/2021', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('3.15', 'USD', '123456780', '900', 'USN0280EAR64', 'Airbus 3.15%  USD', '30/07/2021', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('2', 'USD', '123456bh0', '900', 'A12356111', 'UBS Facebook (USD)', '30/09/2021', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('3.15', 'USD', '123456780', '900', 'USN0280EAR64', 'Airbus 3.15%  USD', '30/07/2021', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('2', 'USD', '123456bh0', '900', 'A12356111', 'UBS Facebook (USD)', '30/09/2021', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('3.15', 'USD', 'AMZN 3.15 08/22/27 REGS', '900', 'USU02320AG12', 'Amazon', '3/8/21', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('3.15', 'USD', 'AMZN 3.15 08/22/27 REGS', '900', 'USU02320AG12', 'Amazon', '3/8/21', 'active', 'CORP');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460505', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460506', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460507', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460508', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460509', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460510', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460511', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460512', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460513', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460514', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('0.75', 'GBP', 'BDCHBW8', '900', 'GB00B6460515', 'HM Treasury United Kingdom', '9/8/21', 'active', 'GOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('2.02', 'USD', '87973RAA8', '690', 'US87973RAA86', 'TEMASEK FINL I LTD GLOBAL MEDIUM TERM NTS BOOK ENTRY REG S', '6/8/21', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('2.02', 'USD', '87973RAA8', '690', 'US87973RAA86', 'TEMASEK FINL I LTD GLOBAL MEDIUM TERM NTS BOOK ENTRY REG S', '6/8/21', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('2.02', 'USD', '87973RAA8', '690', 'US87973RAA86', 'TEMASEK FINL I LTD GLOBAL MEDIUM TERM NTS BOOK ENTRY REG S', '6/8/21', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('2.02', 'USD', '87973RAA8', '690', 'US87973RAA86', 'TEMASEK FINL I LTD GLOBAL MEDIUM TERM NTS BOOK ENTRY REG S', '6/8/21', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('1.123', 'USD', '87973RAA8', '340', 'IE00B29LNP31', 'First Norway Alpha Kl.IV', '22/12/2030', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('1.123', 'USD', '87973RAA8', '340', 'IE00B29LNP31', 'First Norway Alpha Kl.IV', '22/12/2030', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('1.123', 'USD', '87973RAA8', '340', 'IE00B29LNP31', 'First Norway Alpha Kl.IV', '22/12/2030', 'active', 'SOVN');
INSERT INTO security (couponPercent, bondCurrency, cusip, faceValue (mn), isin, issuerName, bondMaturityDate, status, type) VALUES ('1.123', 'USD', '87973RAA8', '340', 'IE00B29LNP31', 'First Norway Alpha Kl.IV', '22/12/2030', 'active', 'SOVN');

INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '50', '4/8/21', 'open', '13/05/2021', '90', '0', '0', '0');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'GBP', '40', '4/8/21', 'open', '4/2/21', '89.56', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '1000', '23/08/2021', 'open', '13/05/2021', '105.775', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'GBP', '900', '10/9/21', 'open', '4/2/21', '105.775', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '50', '23/08/2021', 'open', '13/05/2021', '90', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '1000', '23/08/2021', 'open', '13/05/2021', '105.775', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'USD', '50', '23/08/2021', 'open', '13/05/2021', '90', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '60', '27/09/2021', 'open', '4/2/21', '98.56', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '50', '23/08/2021', 'open', '23/08/2021', '98.56', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '1100', '27/09/2021', 'open', '27/09/2021', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'GBP', '900', '28/09/2021', 'open', '28/09/2021', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '2000', '29/09/2021', 'open', '29/09/2021', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'GBP', '2000', '30/09/2021', 'open', '30/09/2021', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '1000', '1/10/21', 'open', '1/10/21', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '900', '2/10/19', 'open', '2/10/19', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'GBP', '1900', '3/10/19', 'open', '3/10/19', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '600', '4/10/18', 'open', '4/10/18', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '600', '5/10/19', 'open', '5/10/19', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'GBP', '700', '6/6/21', 'open', '6/6/21', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'GBP', '1300', '7/10/21', 'open', '7/10/11', '110.35', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '60', '27/09/2021', 'open', '4/2/12', '100.13', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '50', '23/08/2021', 'open', '23/08/2012', '100.13', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '75', '27/09/2021', 'open', '4/2/13', '100.13', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '50', '23/08/2021', 'open', '23/08/2014', '100.13', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '300', '27/09/2021', 'open', '4/2/16', '98.76', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '300', '23/08/2021', 'open', '23/08/2012', '98.76', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('buy', 'USD', '300', '27/09/2021', 'open', '4/2/13', '98.76', 'null', 'null', 'null');
INSERT INTO tableName (trade_type, trade_currency, quantity, trade_settlement_date, trade_status, trade_date, unit_price, counterPartyID, securityID, bookID) VALUES ('sell', 'USD', '300', '23/08/2021', 'open', '23/08/2015', '98.76', 'null', 'null', 'null');
