DROP TABLE IF EXISTS Bonds;

CREATE TABLE Bonds (
    bond_id INT NOT NULL,
    name VARCHAR(250) NOT NULL,
    age INT NOT NULL
);

DROP TABLE IF EXISTS USERT;

CREATE TABLE USERT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);



